server:
  port: 9100

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/education_site
    username: root
    password: mariadb
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.spring.educationsiteproject.domain
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    com:
      example:
        educationsiteproject: debug